spring.application.name=drinkshop

spring.datasource.url=jdbc:postgresql://localhost:5432/drinkshop
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.model-and-view-allowed=false
springdoc.swagger-ui.path=/swagger-ui.html

supabase.url=https://ydxwwsgwzousllputjeh.supabase.co
supabase.apiKey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkeHd3c2d3em91c2xscHV0amVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzM4NjksImV4cCI6MjA2MDcwOTg2OX0.dDPiPSQ48ss6HGc1FevgR41vMWtnz_FBJvYA0gys0bE

app.jwtExpirationInMs=6000000
server.servlet.session.timeout=5m